- docs/DOCKER.md
The Granite setup guide is a separate sharepoint word doc.  
Update the cfm internal DOCKER.md to match recent changes revolving around the need for cfm-service to automatically restart when a server is unexpectedly rebooted.
Add a docker logs cmd for user convenience.
Add a note for informing a CLI user of the help (-h) option.
> docs: update docker cmds to match granite setup guide

- webui/src/components/Footer.vue
Fetch the cfm service version from the store file, not call the corresponding api. Make the code more concise.
> feat: fetch the cfm service version from the store file

- services/services.go
This removes the os dependency on host ip detection 
This method dials the public dns to see the host IP. 
If the host is in a complete private network, it might fail. 
In this case, the user could use the input argument to specify host IP
> fix: use net module instead of exe os command

- pkg/backend/httpfish.go
- pkg/backend/ops.go
- pkg/manager/appliance.go
- pkg/manager/manager.go
Handle chassis collection with more than one member Check for optional CMA enclosure SN
Pass blade and enclosure SN back to manager layer
User BladeSN as bladeID when customID is not provided
> feat: Use Blade serial number as device ID

- webui/src/components/Dashboard/Dashboard.vue
- webui/src/components/Footer.vue
Call the function to get the cfm-service version in the footer.
Before the fix, this function was called in the Dashboard component, if you refresh in other components, the browser will lose the cfm-service version.
> Get cfm-service version in footer not dashboard

- webui/src/components/Appliance/Appliances.vue
- webui/src/components/CXL-Hosts/CXL-Hosts.vue
- webui/src/components/CXL-Hosts/HostMemory.vue
- webui/src/components/CXL-Hosts/HostMemoryDevice.vue
- webui/src/components/CXL-Hosts/HostPorts.vue
- webui/src/components/Stores/BladeStore.ts
- webui/src/components/Stores/HostStore.ts
Display blade/host status in webui.
Blade online:
Blade offline:
Host online:
Host offline:
> Feat: display blade/host status in webui

- api/cfm-openapi.yaml
- pkg/api/api_default_service.go
- pkg/common/status.go
- pkg/manager/appliance.go
- pkg/manager/manager.go
Added three new APIs(AppliancesRenameById, BladesRenameById, HostsRenameById) to allow the user to rename the devices(appliance/blade/host).
The commands can be used to do testing: 
```
curl -s -X PUT http://localhost:8080/cfm/v1/appliances/{applianceId}?newApplianceId={newApplianceId} | jq
curl -s -X PUT http://localhost:8080/cfm/v1/appliances/{applianceId}/blade/{bladeId}?newBladeId={newBladeId} | jq
curl -s -X PUT http://localhost:8080/cfm/v1/hosts/{hostId}?newHostId={newHostId} | jq
```
> feat: rename appliance/blade/host

- docs/DOCKER.md
The command variable is calling for a docker container name when it should be calling out a docker image name.
Also added additional commands to the customization command sequence to clarify that the custom builds need to happen utilizing the cfm project source code and how to run it after the build
> doc: fix docker doc command variable name

- cli/pkg/serviceLib/serviceRequests/blades.go
Status field of Blade struct is now used for online\offline status reporting.
Add it to the output of `list blades` cmd.
Already present in `list hosts` cmd.
> fix: add online\offline status to output of list blades

- .github/workflows/go.yml
- cmd/cxl-host/service/cxl_host_service.go
Also, add a cxl-host Go build to the CI so syntax errors like this don't find there way into the repo.
> fix(cxl-host): fix syntax error and improve ci

- cmd/cxl-host/main.go
- go.mod
- go.sum
This change adds the cxl-host to register the service port as redfish service in avahi with text "cxl-host=true" for auto discovery
> =   eno1 IPv4 host                                   _obmc_redfish._tcp   local
>    hostname = [host.local]
>    address = [xx.xx.xx.xx]
>    port = [8082]
>    txt = ["cxl-host=true"]
> feat(cxl-host): attempt to publish as avahi service for auto discovery

- api/cfm-openapi.yaml
- pkg/api/api_default_service.go
This feature allows cfm to discover the devices in the network by type (cma or cxl-host).
`dingm@juniper:~/CFM/cfm$ curl -s -X GET http://localhost:8080/cfm/v1/discover?deviceType=cxl-host | jq`
> [
>   {
>     "hostname": "mag-cfm-cxlhost1.local",
>     "address": "10.20.47.243",
>     "port": 8082,
>     "type": "cxl-host"
>   }
> ]
`dingm@juniper:~/CFM/cfm$ curl -s -X GET http://localhost:8080/cfm/v1/discover?deviceType=blade | jq`
> [
>   {
>     "hostname": "granite104.local",
>     "address": "10.20.44.71",
>     "port": 443,
>     "type": "cma"
>   },
>   {
>     "hostname": "granite7.local",
>     "address": "10.20.47.212",
>     "port": 443,
>     "type": "cma"
>   }
> ]
> feat(service): implement new api DiscoverDevices

- api/cfm-openapi.yaml
- docs/DOCKER.md
- pkg/api/api_default_service.go
- pkg/backend/backend.go
- pkg/backend/httpfish.go
- pkg/backend/ops.go
- pkg/manager/blade.go
- pkg/manager/resource.go
This changes gives the frontend client the ability to update the composition status of all blade memory resources blocks in a single call (BladesGetResourceStatus())
Statuses are returned as a collection:
```
type BladesMemoryResourceStatusCollection struct {
StatusCount int32 `json:"statusCount"`
ResourceStatuses []BladesResourceStatus `json:"resourceStatuses"`
}
```
with an array of statuses, with each element looking like:
```
type BladesResourceStatus struct {
Uri string `json:"uri"`
Id string `json:"id"`
CompositionStatus MemoryResourceBlockCompositionStatus `json:"compositionStatus"`
}
``` 
and
```
type MemoryResourceBlockCompositionStatus struct {
CompositionState string `json:"compositionState"`
MaxCompositions int32 `json:"maxCompositions,omitempty"`
NumberOfCompositions int32 …
```
> feat(service): add a consolidated get of memory resource block statuses

- cmd/cxl-host/service/cxl_host_service.go
- pkg/accounts/sessions.go
Changed the cxl-host internal redfish session id's from a simple incrementing integer to a 10 char random alpha-numeric string
> fix(cxl-host): generate unique cxl host session id

- cmd/cfm-service/main.go
- pkg/api/api_default_service.go
- pkg/common/common.go
- pkg/common/datastore/datastore.go
- pkg/manager/appliance.go
- pkg/manager/blade.go
- pkg/manager/host.go
- pkg/manager/manager.go
- services/discovery.go
Add the discovered devices and change the connection status to unavailable for failed devices at the beginning of the cfm-service run, Will change the display color for the unavailable devices in the following work in cfm-webui.
> feat(service): add the discovered devices and change the connection status to unavailable for failed devices

- cmd/cfm-service/main.go
- pkg/api/api_default_service.go
- pkg/common/status.go
- services/discovery.go
When running cfm-service within the std docker container environment, found an error handling problem during device discovery.
CFM docker container goes into infinite restart loop of what's below
```
I1203 20:21:04.436099       1 main.go:53] "[] cfm-service" version="1.x.x" build="2024-12-03T20:20:01"
I1203 20:21:04.436178       1 main.go:55] "cfm-service" args="-webui -verbosity 4"
I1203 20:21:04.436232       1 main.go:56] "cfm-service" settings={"Version":false,"Verbosity":"4","Backend":"httpfish","Port":"8080","Webui":true,"WebuiPort":"3000","HostIpOverride":""}
2024/12/03 20:21:04 Discovered devices of type blade: {0 {<nil> status [500][Unknown] cannot get system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory {500 Unknown}}}
2024/12/03 20:21:04 …
```
> fix(service): fix device discovery error handling during service starup

- webui/src/components/Appliance/Appliances.vue
- webui/src/components/Dashboard/Dashboard.vue
- webui/src/components/Dashboard/initial-control-elements.ts
- webui/src/components/Dashboard/initial-data-elements.ts
- webui/src/components/Dashboard/useLayout.ts
- webui/src/components/Stores/ApplianceStore.ts
- webui/src/components/Stores/HostStore.ts
All discovered devices are added when cfm is initialized, but the user can discover new available devices without restarting the whole cfm by using the `Click to discover new devices` button on the dashboard page.
We prevent the user from manually adding blades to the CMA_Discovered_Blades appliance.
> feat(webui): device discovery in cfm webui

- pkg/manager/appliance.go
- pkg/manager/manager.go
Found a couple bugs in appliance.AddBlade() and manager.AddHost(). 
(1) corner case where an empty bladeId is being allowed, when it shouldn't 
(2) Not enough information is being saved to new blade objects during error handling.  This was causing a panic during the delete because the backendOps variable was a nil point being used to call a backend function.
> fix(service): fix error handling bugs during add blade\host

- webui/package-lock.json
- webui/package.json
Implementing multiple security updates.
The first updates came from (#64) and (#69).
Both of these PR's are combined into this PR.
Then, also ran `npm audit fix` to fix additional security vulnerabilities not yet flagged by `mend-for-github` or `dependabot` bots.
Note: The `package.json` file update was manual.  All "lock" file updates were implemented by `npm audit fix`.
> build(deps): implement webui security updates

- webui/src/components/Dashboard/Dashboard.vue
- webui/src/components/Dashboard/initial-control-elements.ts
- webui/src/components/Dashboard/initial-data-elements.ts
- webui/src/components/Dashboard/useLayout.ts
- webui/src/components/Stores/ApplianceStore.ts
- webui/src/components/Stores/HostStore.ts
Fixed issue where when getting blade by id failed, all the blades in the same appliance and the associated appliance are also not displayed in the dashboard. And the same for failed hosts.
> fix(webui): make failed blade or host not affect the display of other devices

- webui/src/components/Appliance/Appliances.vue
- webui/src/components/CXL-Hosts/CXL-Hosts.vue
Set up the layout for offline devices and the unknown status devices. If one device is not online, offline or unavailable status, it will be regraded as default unknown with gray color.
> fix: change the layout for the offline devices

- pkg/manager/appliance.go
- pkg/manager/manager.go
Remove the adding of a blade\host to the service's internal map and datastore when the backend create session fails.  This code was inadvertently allowing blades\hosts to be added that were not real.
> fix(service): update add-blade\host error handling

- webui/src/components/Dashboard/Dashboard.vue
Display of failed added devices in the dashboard.
Changed the results popup when adding new devices. Place a circle icon in front of successful devices and a circle icon in front of failed devices.
Old:
New:
> feat(webui): display of failed added devices in the dashboard

- webui/src/components/Appliance/Memory.vue
When assigning an existing memory region to a specific port, if the user forgets to select the port, the system will continue the assignment process but won’t perform any action. The new code changes this behavior to display a failure popup in such scenario.
> fix(webui): resolve the assign port empty issue

- Makefile
Folder not currently used and has conflict with generated path (github.com/GIT_USER_ID/GIT_REPO_ID/client) that causes `go mod tidy` to show a failure,
> fix: tweak makefile to delete unused\conflicting generated code

- webui/package.json
The CJS build of Vite's Node API is deprecated and will be removed in Vite 6. Need to update files or frameworks to import the ESM build of Vite instead.
The "vite" package will only export ESM code:
```
// ✅ Works
import { ... } from "vite"
// ✅ Works
const { ... } = await import("vite")
// ❌ Will not work
const { ... } = require("vite")
```
Here is the refer: https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated
> chore(webui): move Vite's Node API as ESM only
